### ISSUE TITLE
May I study your paper related to the program? 

### ISSUE THREAD

**Issue by AjayTsao** [stuart-morrison/CorrelationPlusContagion#1]
May I study your paper related to the program?  I cannot download from the web.  Or you can send it to my email 377903927@qq.com

**Comment by stuart-morrison** [comment]
Sorry for delay - I have uploaded the pdf into the repository and below. Careful with applying the code - this was an undergrad thesis at the start of my Rlang adventures.
[Stuart_Morrison_42657927_ECON6910.pdf](https://github.com/stuart-morrison/CorrelationPlusContagion/files/3147293/Stuart_Morrison_42657927_ECON6910.pdf)
